spring.application.name=auth-service

server.port=8083

# ==========================================
# PostgreSQL Database
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/smartbank_db
spring.datasource.username=postgres
spring.datasource.password=postgres


# ==========================================
# JPA / Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# PostgreSQL Schema
# ==========================================
spring.jpa.properties.hibernate.default_schema=auth_schema


logging.level.org.springframework.security=DEBUG


#==========================================
# JWT Configuration
#==========================================
jwt.secret=vlEU6kaaJj6B2RbMIfOgdZZSDuQyH2rBtMxuMQtCc0U=
jwt.expiration=900000
jwt.issuer=smartbank-auth-service
