services:

  redis:
    image: redis:7-alpine
    container_name: smartbank-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - smartbank-redis-data:/data
    command: redis-server --appendonly yes

  kafka:
    image: apache/kafka:4.0.1
    container_name: smartbank-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      # KRaft mode - no ZooKeeper
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    volumes:
      - smartbank-kafka-data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: smartbank-kafka-ui
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: smartbank
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

volumes:

  smartbank-redis-data:
    name: smartbank-redis-data

  smartbank-kafka-data:
    name: smartbank-kafka-data