spring.application.name=transaction-service

server.port=8084

# ==========================================
# PostgreSQL Database
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/smartbank_db
spring.datasource.username=postgres
spring.datasource.password=postgres


# ==========================================
# JPA / Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# PostgreSQL Schema
# ==========================================
spring.jpa.properties.hibernate.default_schema=transaction_schema

#==========================================
# Actuator
#==========================================
management.endpoints.web.exposure.include=health,info

# =========================
# Kafka
# =========================

spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Consumer
spring.kafka.consumer.group-id=transaction-audit-consumer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

#Needed for JsonDeserializer to work properly, otherwise it will throw an exception
#spring.kafka.consumer.properties.spring.json.trusted.packages=com.smartbank.transaction.event
#spring.kafka.consumer.properties.spring.json.value.default.type=com.smartbank.transaction.event.TransactionCreatedEvent
#spring.kafka.consumer.properties.spring.json.use.type.headers=false

# =========================
# Outbox
# =========================

outbox.publisher.fixed-delay-ms=5000
outbox.publisher.max-retries=3