server.port=${SERVER_PORT:8080}

spring.application.name=${APP_NAME:api-gateway}

# ==============================
# Auth Service Route
# ==============================
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

# ==============================
# Customer Service Route
# ==============================
spring.cloud.gateway.routes[1].id=customer-service
spring.cloud.gateway.routes[1].uri=${CUSTOMER_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/customers/**

# ==============================
# Account Service Route
# ==============================
spring.cloud.gateway.routes[2].id=account-service
spring.cloud.gateway.routes[2].uri=${ACCOUNT_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/accounts/**

#=============================
# Transaction Service Route
#=============================
spring.cloud.gateway.routes[3].id=transaction-service
spring.cloud.gateway.routes[3].uri=${TRANSACTION_SERVICE_URL:http://localhost:8084}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/transactions/**

spring.cloud.gateway.routes[4].id=transaction-outbox-replay
spring.cloud.gateway.routes[4].uri=${TRANSACTION_SERVICE_URL:http://localhost:8084}
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/internal/outbox/**

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS:health,info,metrics,prometheus}
management.endpoint.health.show-details=${MANAGEMENT_HEALTH_DETAILS:always}

# Enable histogram buckets for HTTP request latency
management.metrics.distribution.percentiles-histogram.http.server.requests=${METRICS_HTTP_LATENCY_HISTOGRAM:true}

# ==============================
# Logging
# ==============================
logging.level.org.springframework.cloud.gateway=${GATEWAY_LOG_LEVEL:INFO}

# ==============================
# JWT
# ==============================
jwt.secret=${JWT_SECRET}