spring.application.name=${APP_NAME:customer-service}
# ==========================================
# Server
# ==========================================
server.port=${SERVER_PORT:8081}

#==========================================
# Redis Configuration
#==========================================
spring.redis.host=${REDIS_HOST:localhost}
spring.redis.port=${REDIS_PORT:6379}

# ==========================================
# PostgreSQL Database
# ==========================================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/smartbank_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# ==========================================
# JPA / Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:false}

# ==========================================
# PostgreSQL Schema
# ==========================================
spring.jpa.properties.hibernate.default_schema=${CUSTOMER_SCHEMA:customer_schema}

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS:health,info,metrics,prometheus}
management.endpoint.health.show-details=${MANAGEMENT_HEALTH_DETAILS:always}

# Enable histogram buckets for HTTP request latency
management.metrics.distribution.percentiles-histogram.http.server.requests=${METRICS_HTTP_LATENCY_HISTOGRAM:true}

# ===============================
# Application Info
# ===============================
info.app.name=${INFO_APP_NAME:SmartBank Customer Service}
info.app.description=${INFO_APP_DESCRIPTION:Customer management microservice}
info.app.version=${INFO_APP_VERSION:1.0.0}