spring.application.name=customer-service
# ==========================================
# Server
# ==========================================
server.port=8081

#==========================================
# Redis Configuration
#==========================================
spring.redis.host=localhost
spring.redis.port=6379


# ==========================================
# PostgreSQL Database
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/smartbank_db
spring.datasource.username=postgres
spring.datasource.password=postgres


# ==========================================
# JPA / Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# PostgreSQL Schema
# ==========================================
spring.jpa.properties.hibernate.default_schema=customer_schema

# ===============================
# Actuator
# ===============================

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# ===============================
# Application Info
# ===============================

info.app.name=SmartBank Customer Service
info.app.description=Customer management microservice
info.app.version=1.0.0